---

## Note: python pip doesn't address missing devel packages required for building like libssl-dev, libffi-dev, ...
- name: check python pip installed
  command: which pip
  changed_when: false
  ignore_errors: true
  register: pip1
  tags: pip
- name: get outdated python packages
  shell: "pip list --outdated 2>/dev/null | awk '!/{{ upgradepkgspip_pip_exclude }}/ { print $1 }'"
  register: piplist
  changed_when: false
  ignore_errors: true
  tags: pip

#- debug: var=piplist
- block:
    - name: Linux | ensure libssl-dev is installed (cryptography, paramiko...)
      package: name=libssl-dev state=present
      when: ansible_system == 'Linux'
    - name: upgrade python pip itself
      pip: name=pip state=latest
      #command: "pip install -U pip"
      #command: "python -m pip install -U pip"
    - name: update system python pip packages
      pip:
        name: "{{ item }}"
        state: latest
        extra_args: "--log {{ upgradepkgspip_pip_log }}"
      with_items: "{{ piplist.stdout_lines }}"
      ignore_errors: true
    - name: set pip_updated var
      set_fact:
        pip_updated: true
  when: pip1 is defined and pip1.stdout is defined and pip1.stdout.find("/usr") != -1 and piplist.stdout != ''

