---

## Note: python pip doesn't address missing devel packages required for building like libssl-dev, libffi-dev, ...
- name: Check python pip installed
  ansible.builtin.command: which pip
  changed_when: false
  ignore_errors: true
  register: pip1
  tags: pip
- name: Get outdated python packages
  ansible.builtin.shell: "pip list --outdated 2>/dev/null | awk '!/{{ upgradepkgspip_pip_exclude }}/ { print $1 }'"
  register: piplist
  changed_when: false
  ignore_errors: true
  tags: pip

# - debug: var=piplist
- name: Pip
  block:
    - name: Linux | ensure libssl-dev is installed (cryptography, paramiko...)
      ansible.builtin.package: name=libssl-dev state=present
      when: ansible_system == 'Linux'
      register: pkg_result
      until: pkg_result is success
    - name: Upgrade python pip itself
      ansible.builtin.pip:  # noqa package-latest
        name: pip
        state: latest
      # command: "pip install -U pip"
      # command: "python -m pip install -U pip"
      register: pkg_result
      until: pkg_result is success
    - name: Update system python pip packages
      ansible.builtin.pip:  # noqa package-latest
        name: "{{ piplist.stdout_lines }}"
        state: latest
        extra_args: "--log {{ upgradepkgspip_pip_log }}"
      ignore_errors: true
      register: pkg_result
      until: pkg_result is success
    - name: Set pip_updated var
      ansible.builtin.set_fact:
        pip_updated: true
  when: pip1 is defined and pip1.stdout is defined and pip1.stdout.find("/usr") != -1 and piplist.stdout
